### ISSUE TITLE
Have old URLs like `/irc` and `/join` work

### ISSUE THREAD

**Issue by allc** [compsoc-edinburgh/comp-soc.com#19]
I still see these links referenced at places
For `/join` propose to redirect to EUSA CompSoc membership page, through the website or Cloudflare (temporary) redirect rules

**Comment by tomasmaillo** [comment]
@Cat2005 is this something you could look into?

**Comment by allc** [comment]
Btw, creating a page rule like this on Cloudflare would make URLs like https://comp-soc.com/blog/2024/03/21/2024-agm-manifestos.html from old website which referenced in [some posts](https://comp-soc.com/news/2024-03-20-april-agm/) redirect to ones on the new website like https://comp-soc.com/news/2024-03-21-2024-agm-manifestos/ if also want to
![image](https://github.com/user-attachments/assets/2d11d6a1-9d83-42ff-9065-8ccefbb4d309)

**Comment by tomasmaillo** [comment]
`/irc` issue i addressed in 3aa9054a1787ac94985943ddc9114a892c17728b !!!!

**Comment by qaisjp** [comment]
I suggest trying to put these redirects in the code (if possible) instead of in Cloudflare configuration, so that it's easier to reference to later when the Cloudflare configuration is inevitably lost

**Comment by tomasmaillo** [comment]
Yeah, good point. Smarter to keep control on the code side rather than some Cloudflare config!

Just added a redirect for [`comp-soc.com/join`](https://comp-soc.com/join) pointing to EUSA on 51ba50632be102f1aefe3f51fc6129c8b500acf6

**Comment by tomasmaillo** [comment]
Both `/irc` and `/join` are up. Are there any other routes that we should implement @allc ?

**Comment by allc** [comment]
Not on top of my head. Thank you for adding those back <3

Fyi `/discord` is currently configured through Cloudflare (been there since
the old website)

**Comment by tomasmaillo** [comment]
Oh interesting. I did not know about that one. 

Maybe there is an argument to be made that all special routes should be on the same place (either Cloudflare or website)

Thanks sm! I'll close this now as we cant think of other routes :)
