### ISSUE TITLE
README revamp! (Good first issue)

### ISSUE THREAD

**Issue by tomasmaillo** [compsoc-edinburgh/comp-soc.com#23]
Readme needs to be revamped with instructions. 

To add:
- How to install Node 
- How to clone project
- How to run the project
- How to contribute
- How to add meeting minutes and news posts (`.md`)

**Comment by Bala-kumaran-S** [comment]
can you assgin this to me

**Comment by tomasmaillo** [comment]
Done! Thank you for taking this on :) Go crazy go wild! 
Let me know if you have any questions

**Comment by Bala-kumaran-S** [comment]
how to run the project in my local machine
i have installed the needed packages and could you give a brief description about the project

**Comment by tomasmaillo** [comment]
Now that the packages are installed, you would need to run `npm run dev` ! That should be all :)

**Comment by Bala-kumaran-S** [comment]
Could you explain me about meeting minutes and news post?

**Comment by tomasmaillo** [comment]
Within the folder `/constants` there are the folders `/minutes` and `/news`. Both of these hold `.md` files that get rendered into pages. Here is an example of [meeting minutes `.md`](https://github.com/compsoc-edinburgh/comp-soc.com/blob/main/constants/minutes/2024-10-11.md) converted into a [page](https://comp-soc.com/minutes/2024-10-11/).

To add new meeting minutes or news articles a contributor would need to create a new `.md` file in the corresponding folder. They would then need to open a PR to get their changes merged.

**Comment by Bala-kumaran-S** [comment]
Made the pull request.
If you want any changes please let me know.

**Comment by Bala-kumaran-S** [comment]
? ? ? its been three days.why no reply.

**Comment by Bala-kumaran-S** [comment]
you can tell me if you need any changes

**Comment by tomasmaillo** [comment]
> its been three days.why no reply.

I left a review comment on the #25 2 days ago. (Also, I'm quite busy)

**Comment by Bala-kumaran-S** [comment]
take your time.
