### ISSUE TITLE
Allow `radius: 0px` for SIG logos

### ISSUE THREAD

**Issue by jacobjwalters** [compsoc-edinburgh/comp-soc.com#5]
Currently, [types/SIG.d.ts](https://github.com/compsoc-edinburgh/comp-soc.com/blob/3e5579a61762e6fc852b0730e15a7dd14e2bfbf0/types/SIG.d.ts#L14) specifies a boolean value `rounded` for `SIGIcon`, which eventually resolves to applying [either `rounded-full` or `rounded-lg`](https://github.com/compsoc-edinburgh/comp-soc.com/blob/3e5579a61762e6fc852b0730e15a7dd14e2bfbf0/components/SIGCards/SIGCard.tsx#L36) to the logo. Some SIG logos, including TypeSig's, are not supposed to have a corner rounding applied to them.

Proposed solution: add a three-way sum type that allows choice between a circular logo, rounded corners, or no rounding at all. This should still allow rounding to be consistent between SIG logos when applied.

**Comment by tomasmaillo** [comment]
Hiya Jacob! Good point. Ive added those changes now :)
